services:
  - type: web
    name: repovacio-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: repovacio-db
          property: connectionString
      - key: UPLOADS_DIR
        value: /app/uploads
      - key: AUTH_SECRET
        generateValue: true
      - key: AUTH_URL
        sync: false
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: ADMIN_EMAIL
        value: soyadmin@admin.com
      - key: ADMIN_PASSWORD
        value: "0987654321"
      - key: ADMIN_NAME
        value: Administrador
      - key: APP_NAME
        value: White Label

databases:
  - name: repovacio-db
    plan: free
    databaseName: whitelabel
    user: whitelabel
